# Generated by Django 3.1 on 2020-11-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'following')},
        ),
    ]
